name: Scraping
 
on:
  schedule:
    - cron: '0 7 */2 * *'  # At 07:00 on every day-of-month
    
jobs:
  rumor-scrape:
    runs-on: windows-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version 
    - uses: r-lib/actions/setup-r@v2   
    - name: Install packages
      run: |
        install.packages("RSelenium")
        install.packages("netstat", dependencies = TRUE)
        install.packages("wdman", dependencies = TRUE)
        install.packages("rvest", dependencies = TRUE)
        install.packages("tidyverse", dependencies = TRUE)
        install.packages("binman")
      shell: Rscript {0} 
    - name: Scrape Data Transfermarkt Rumour to MongoDB Atlas
      run: Rscript transfermarkt-rumour-scrape.R
